site_name: Algorytmy i struktury danych
theme: readthedocs
markdown_extensions:
    - markdown.extensions.codehilite:
          guess_lang: false
    - markdown.extensions.fenced_code
nav:
    - O notatkach: index.md
    - Powtórzenie z dyskretnej: mdl/md.md
    - Struktury danych:
          - Kopce:
                - Kopiec minimalny/maksymalny: binary-heap/binary-heap.md
                - Kopiec min-max: min-max-heap/min-max-heap.md
    - Algorytmy:
          - zachłanne: greedy/greedy-algos.md
