site_name: Algorytmy i struktury danych
theme: readthedocs
markdown_extensions:
    - markdown.extensions.codehilite:
          guess_lang: false
    - markdown.extensions.fenced_code

extra_javascript:
    - js/extra.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - O notatkach: index.md
    - Kolejność: order.md
    - Powtórzenie z dyskretnej: mdl/md.md
    - Struktury danych:
          - kopiec:
                - minimalny/maksymalny: heaps/binary/binary-heap.md
                - min-max: heaps/min-max/min-max-heap.md
                - dwumianowy: heaps/binomial/binomial-heap.md
                - Fibonacciego: heaps/fibonacci/fibonacci-heaps.md
          - drzewo:
                - AVL: trees/avl.md
                - B: trees/b-trees.md
                - czerwono-czarne: trees/red-black.md
                - splay: trees/splay.md
                - union-find: trees/union-find.md
          - słownik statyczny: static-dict/static-dict.md
    - Algorytmy:
          - zachłanne: greedy/greedy-algos.md
          - dziel i zwyciężaj: divide-and-conquer/dac-algos.md
          - dynamiczne: dynamic/dynamic.md
          - sortujące: sorting/sorting.md
          - selekcja: selection/selection.md
          - wyszukujące wzorzec: string-searching/string-searching.md
    - Inne (ale też ważne):
          - dolne granice: bounds/bottom-bounds.md
          - haszowanie: hashing/hashing.md
