site_name: Algorytmy i struktury danych
theme: readthedocs
markdown_extensions:
    - markdown.extensions.codehilite:
          guess_lang: false
    - markdown.extensions.fenced_code

extra_javascript:
    - js/extra.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - O notatkach: index.md
    - Kolejność: order.md
    - Powtórzenie z dyskretnej: mdl/md.md
    - Struktury danych:
          - Kopce:
                - Kopiec minimalny/maksymalny: binary-heap/binary-heap.md
                - Kopiec min-max: min-max-heap/min-max-heap.md
          - Drzewa:
                - AVL: trees/avl.md
                - B: trees/b-trees.md
                - czerwono-czarne: trees/red-black.md
    - Algorytmy:
          - zachłanne: greedy/greedy-algos.md
          - dziel i zwyciężaj: divide-and-conquer/dac-algos.md
          - dynamiczne: dynamic/dynamic.md
          - sortujące: sorting/sorting.md
          - selekcja: selection/selection.md
    - Inne (ale też ważne):
          - dolne granice: bounds/bottom-bounds.md
